FROM nginx:alpine

RUN rm /usr/share/nginx/html/index.html

COPY index.html /usr/share/nginx/html/index.html

# Change ownership of Nginx directories to allow OpenShift's non-root user
RUN chown -R 1001:0 /var/cache/nginx /var/run /usr/share/nginx/html && \
    chmod -R g+w /var/cache/nginx /var/run /usr/share/nginx/html

# Switch to non-root user used in OpenShift containers
USER 1001

EXPOSE 8080
