FROM nginx:1.25-alpine

COPY index.html /usr/share/nginx/html/index.html
COPY nginx.conf /etc/nginx/nginx.conf

RUN chown -R 1001:0 /usr/share/nginx/html /etc/nginx && \
    chmod -R g+w /usr/share/nginx/html /etc/nginx

